const userReturn = {
  avatar_url: "https://avatars3.githubusercontent.com/u/47114646?v=4"
  bio: "Touring musician turned Software Engineer JS | React | Node | Python"
  blog: "http://www.gregorycjohnston.com/"
  company: null
  created_at: "2019-01-28T15:48:03Z"
  email: null
  events_url: "https://api.github.com/users/GCJ2/events{/privacy}"
  followers: 13
  followers_url: "https://api.github.com/users/GCJ2/followers"
  following: 23
  following_url: "https://api.github.com/users/GCJ2/following{/other_user}"
  gists_url: "https://api.github.com/users/GCJ2/gists{/gist_id}"
  gravatar_id: ""
  hireable: null
  html_url: "https://github.com/GCJ2"
  id: 47114646
  location: "South Carolina"
  login: "GCJ2"
  name: "Greg Johnston"
  node_id: "MDQ6VXNlcjQ3MTE0NjQ2"
  organizations_url: "https://api.github.com/users/GCJ2/orgs"
  public_gists: 0
  public_repos: 130
  received_events_url: "https://api.github.com/users/GCJ2/received_events"
  repos_url: "https://api.github.com/users/GCJ2/repos"
  site_admin: false
  starred_url: "https://api.github.com/users/GCJ2/starred{/owner}{/repo}"
  subscriptions_url: "https://api.github.com/users/GCJ2/subscriptions"
  twitter_username: "GregIsLiving"
  type: "User"
  updated_at: "2020-06-22T17:12:02Z"
  url: "https://api.github.com/users/GCJ2"
  __proto__: Object
};

const repoReturn = {
  archive_url: "https://api.github.com/repos/GCJ2/Algorithms/{archive_format}{/ref}"
  archived: false
  assignees_url: "https://api.github.com/repos/GCJ2/Algorithms/assignees{/user}"
  blobs_url: "https://api.github.com/repos/GCJ2/Algorithms/git/blobs{/sha}"
  branches_url: "https://api.github.com/repos/GCJ2/Algorithms/branches{/branch}"
  clone_url: "https://github.com/GCJ2/Algorithms.git"
  collaborators_url: "https://api.github.com/repos/GCJ2/Algorithms/collaborators{/collaborator}"
  comments_url: "https://api.github.com/repos/GCJ2/Algorithms/comments{/number}"
  commits_url: "https://api.github.com/repos/GCJ2/Algorithms/commits{/sha}"
  compare_url: "https://api.github.com/repos/GCJ2/Algorithms/compare/{base}...{head}"
  contents_url: "https://api.github.com/repos/GCJ2/Algorithms/contents/{+path}"
  contributors_url: "https://api.github.com/repos/GCJ2/Algorithms/contributors"
  created_at: "2020-04-22T13:25:52Z"
  default_branch: "Greg-Johnston"
  deployments_url: "https://api.github.com/repos/GCJ2/Algorithms/deployments"
  description: null
  disabled: false
  downloads_url: "https://api.github.com/repos/GCJ2/Algorithms/downloads"
  events_url: "https://api.github.com/repos/GCJ2/Algorithms/events"
  fork: false
  forks: 0
  forks_count: 0
  forks_url: "https://api.github.com/repos/GCJ2/Algorithms/forks"
  full_name: "GCJ2/Algorithms"
  git_commits_url: "https://api.github.com/repos/GCJ2/Algorithms/git/commits{/sha}"
  git_refs_url: "https://api.github.com/repos/GCJ2/Algorithms/git/refs{/sha}"
  git_tags_url: "https://api.github.com/repos/GCJ2/Algorithms/git/tags{/sha}"
  git_url: "git://github.com/GCJ2/Algorithms.git"
  has_downloads: true
  has_issues: true
  has_pages: false
  has_projects: true
  has_wiki: true
  homepage: null
  hooks_url: "https://api.github.com/repos/GCJ2/Algorithms/hooks"
  html_url: "https://github.com/GCJ2/Algorithms"
  id: 257909031
  issue_comment_url: "https://api.github.com/repos/GCJ2/Algorithms/issues/comments{/number}"
  issue_events_url: "https://api.github.com/repos/GCJ2/Algorithms/issues/events{/number}"
  issues_url: "https://api.github.com/repos/GCJ2/Algorithms/issues{/number}"
  keys_url: "https://api.github.com/repos/GCJ2/Algorithms/keys{/key_id}"
  labels_url: "https://api.github.com/repos/GCJ2/Algorithms/labels{/name}"
  language: "Python"
  languages_url: "https://api.github.com/repos/GCJ2/Algorithms/languages"
  license: null
  merges_url: "https://api.github.com/repos/GCJ2/Algorithms/merges"
  milestones_url: "https://api.github.com/repos/GCJ2/Algorithms/milestones{/number}"
  mirror_url: null
  name: "Algorithms"
  node_id: "MDEwOlJlcG9zaXRvcnkyNTc5MDkwMzE="
  notifications_url: "https://api.github.com/repos/GCJ2/Algorithms/notifications{?since,all,participating}"
  open_issues: 0
  open_issues_count: 0
  private: false
  pulls_url: "https://api.github.com/repos/GCJ2/Algorithms/pulls{/number}"
  pushed_at: "2020-04-22T13:26:01Z"
  releases_url: "https://api.github.com/repos/GCJ2/Algorithms/releases{/id}"
  size: 46
  ssh_url: "git@github.com:GCJ2/Algorithms.git"
  stargazers_count: 0
  stargazers_url: "https://api.github.com/repos/GCJ2/Algorithms/stargazers"
  statuses_url: "https://api.github.com/repos/GCJ2/Algorithms/statuses/{sha}"
  subscribers_url: "https://api.github.com/repos/GCJ2/Algorithms/subscribers"
  subscription_url: "https://api.github.com/repos/GCJ2/Algorithms/subscription"
  svn_url: "https://github.com/GCJ2/Algorithms"
  tags_url: "https://api.github.com/repos/GCJ2/Algorithms/tags"
  teams_url: "https://api.github.com/repos/GCJ2/Algorithms/teams"
  trees_url: "https://api.github.com/repos/GCJ2/Algorithms/git/trees{/sha}"
  updated_at: "2020-04-22T13:26:06Z"
  url: "https://api.github.com/repos/GCJ2/Algorithms"
  watchers: 0
  watchers_count: 0
}

const followerReturn = {
  avatar_url: "https://avatars2.githubusercontent.com/u/51802989?v=4"
  events_url: "https://api.github.com/users/thetaylorjacobs/events{/privacy}"
  followers_url: "https://api.github.com/users/thetaylorjacobs/followers"
  following_url: "https://api.github.com/users/thetaylorjacobs/following{/other_user}"
  gists_url: "https://api.github.com/users/thetaylorjacobs/gists{/gist_id}"
  gravatar_id: ""
  html_url: "https://github.com/thetaylorjacobs"
  id: 51802989
  login: "thetaylorjacobs"
  node_id: "MDQ6VXNlcjUxODAyOTg5"
  organizations_url: "https://api.github.com/users/thetaylorjacobs/orgs"
  received_events_url: "https://api.github.com/users/thetaylorjacobs/received_events"
  repos_url: "https://api.github.com/users/thetaylorjacobs/repos"
  site_admin: false
  starred_url: "https://api.github.com/users/thetaylorjacobs/starred{/owner}{/repo}"
  subscriptions_url: "https://api.github.com/users/thetaylorjacobs/subscriptions"
  type: "User"
  url: "https://api.github.com/users/thetaylorjacobs"
}